export const authAppearance = {
  variables: {
    colorPrimary: "#e50914",
    colorBackground: "transparent",
    colorText: "#ffffff",
    colorTextSecondary: "#d4d4d8",
    colorInputBackground: "rgba(255, 255, 255, 0.08)",
    colorInputText: "#ffffff",
    borderRadius: "4px",
  },
  elements: {
    cardBox: "bg-transparent shadow-none",
    card: "bg-transparent shadow-none",
    headerTitle: "text-white",
    headerSubtitle: "text-[#d4d4d8]",
    formFieldLabel: "text-[#f5f5f5]",
    formFieldInput: "border-white/20 bg-white/10 text-white placeholder:text-[#8c8c8c] focus:border-[#e50914]",
    formFieldInputShowPasswordButton: "text-white",
    formFieldAction: "text-white hover:text-[#e50914]",
    identityPreviewText: "text-white",
    identityPreviewEditButton: "text-[#e50914]",
    footerActionText: "text-[#d4d4d8]",
    footerActionLink: "text-white hover:text-[#e50914]",
    dividerText: "text-[#d4d4d8]",
    socialButtonsBlockButton: "border-white/20 bg-white/10 text-white hover:bg-white/15",
    socialButtonsBlockButtonText: "text-white",
    formButtonPrimary: "bg-[#e50914] text-white hover:bg-[#f6121d]",
  },
};
